validate error

diff --git a/.github/workflows/other-branch.yml b/.github/workflows/other-branch.yml
--- a/.github/workflows/other-branch.yml
+++ b/.github/workflows/other-branch.yml
@@ -7,6 +7,15 @@ on:
 
 jobs:
 
+  error:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Imprimir mensaje de error
+        run: |
+          echo "Este jobs genero un error"
+          exit 1
+
 
   build:
     runs-on: ubuntu-latest
@@ -23,13 +32,6 @@ jobs:
         run: echo "Run Test"
         
 
-  error:
-    runs-on: ubuntu-latest
 
-    steps:
-      - name: Imprimir mensaje de error
-        run: |
-          echo "Este jobs genero un error"
-          exit 1
 
 
